---
- hosts: aggregator-machine
  vars:
    setup_env: bash -x stack/setup.sh               
    deploy_stack: bash -x stack/deploy-stack.sh    
  tasks:     
    - name: Copy Swarm Files
      copy: src="../stack/" dest="/home/ubuntu/stack"  

    - name: Setting up environment
      shell: "{{ setup_env }}"
      become: yes          

    - name: Deploy Stack of Services
      shell: "{{ deploy_stack }}"
      become: yes

    - name: Cleaning up
      shell: rm -rf .ansible/ stack/
      become: yes
