global:
  scrape_interval:     15s
  evaluation_interval: 30s  

scrape_configs:
- job_name: pushgateway
  scrape_interval: 5s
  honor_labels: true
  static_configs:
    - targets: ['pushgateway:9091']